<?php

declare(strict_types=1);

namespace Globetrotters\AiPresenceBundle\Serving;

use Globetrotters\AiPresenceBundle\Cache\ArtefactCache;
use Globetrotters\AiPresenceBundle\Settings\Options;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Event\ExceptionEvent;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\KernelEvents;

/**
 * Serves a generated ``/sitemap.xml`` **only when the application has none**.
 *
 * This is why the sitemap is not a {@see Router} route. Router runs on
 * kernel.request at priority 64, ahead of routing, precisely so nothing can
 * claim the artefact paths — pre-emption is the point there, and no application
 * serves ``/llms.txt`` or an IndexNow key file. Plenty of them serve
 * ``/sitemap.xml``, and that one is theirs: it is a manifest of *their* site,
 * usually generated by a bundle that knows every route, and replacing it with a
 * six-URL listing of discovery documents would be a straight loss. So this
 * subscriber takes the shape {@see RobotsFilter} already uses for the other
 * file an application may own — the 404 lanes, and nothing else.
 *
 * The 200 case is a deliberate no-op rather than a decoration. Appending
 * ``<url>`` entries before ``</urlset>`` would work on a plain sitemap, but not
 * on the installs that most often have one: a ``<sitemapindex>`` has no
 * ``</urlset>``, a large sitemap is commonly streamed or gzipped, and a
 * ``public/sitemap.xml`` never reaches the kernel at all. Behaviour that
 * applies on some installs and silently not on others is worse than one clear
 * rule, and nothing is lost — ``llms.txt`` already links the discovery surface,
 * and the ``Sitemap:`` line {@see RobotsFilter} emits names this host either
 * way.
 *
 * Same limitation as robots: a physical ``public/sitemap.xml`` is served by the
 * web server and never reaches the kernel — which here produces exactly the
 * intended outcome.
 */
final class SitemapFallback implements EventSubscriberInterface
{
    private const PATH = '/'.Sitemap::PATH;

    public function __construct(
        private readonly Options $options,
        private readonly ArtefactCache $cache,
        private readonly Sitemap $sitemap,
    ) {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::RESPONSE => ['onKernelResponse', -20],
            KernelEvents::EXCEPTION => ['onKernelException', 0],
        ];
    }

    /**
     * Generate when the app returned an explicit 404 Response (a catch-all
     * controller that returns rather than throws — the thrown case is handled
     * in onKernelException instead). A 200 is the application's own sitemap and
     * is left exactly as it is.
     */
    public function onKernelResponse(ResponseEvent $event): void
    {
        $request = $event->getRequest();
        if (!$event->isMainRequest() || !$this->applies($request)) {
            return;
        }

        $response = $event->getResponse();
        if (404 !== $response->getStatusCode()) {
            return;
        }

        $body = $this->sitemap->render($request->getSchemeAndHttpHost());
        if ('' === $body) {
            return;
        }

        $response->setStatusCode(200);
        // Symfony's ResponseListener runs at priority 0, above this one, and its
        // Response::prepare() has already emptied the body of a HEAD response —
        // writing one back here would put bytes on a HEAD. The exception lane
        // below is prepared *after* it sets the response, so it needs no such
        // guard.
        $response->setContent('HEAD' === $request->getMethod() ? '' : $body);
        $response->headers->add(self::headers());
        BodyMetadata::invalidate($response, $request);
    }

    public function onKernelException(ExceptionEvent $event): void
    {
        $request = $event->getRequest();
        if (!$event->isMainRequest() || !$this->applies($request)) {
            return;
        }
        if (!$event->getThrowable() instanceof NotFoundHttpException) {
            return;
        }

        $body = $this->sitemap->render($request->getSchemeAndHttpHost());
        if ('' === $body) {
            return;
        }

        // Without this the kernel would force the response status back to the
        // exception's 404 (see HttpKernel::handleThrowable).
        $event->allowCustomResponseCode();
        $event->setResponse(new Response($body, 200, self::headers()));
    }

    /**
     * The body embeds the origin this very request arrived on, so it must not
     * be reused for another: a host alias sharing a cache entry would be
     * advertised a sitemap full of the other host's URLs. Same constant the
     * artefacts use, for a different reason — generating the document costs one
     * cache read and no I/O, so there is nothing to protect by caching it.
     *
     * @return array<string, string>
     */
    private static function headers(): array
    {
        return ['Content-Type' => Sitemap::CONTENT_TYPE] + Router::NO_STORE_HEADERS;
    }

    /**
     * Cheap structural tests first: the cache and state reads only happen for a
     * request that could actually be answered here.
     */
    private function applies(Request $request): bool
    {
        return self::PATH === $request->getPathInfo()
            && \in_array($request->getMethod(), ['GET', 'HEAD'], true)
            && $this->options->isConnected()
            && $this->cache->hasAny();
    }
}
